// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbKnkUgRNrkIOHVs9Px3XGzVbT25bWqjY',
    appId: '1:889957862081:web:53d27eefe11e712d102240',
    messagingSenderId: '889957862081',
    projectId: 'shuttlelink-app-c593c',
    authDomain: 'shuttlelink-app-c593c.firebaseapp.com',
    databaseURL: 'https://shuttlelink-app-c593c-default-rtdb.firebaseio.com',
    storageBucket: 'shuttlelink-app-c593c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeERj-oYhDXVhZiRQauMcFqNEnvP7aqo',
    appId: '1:889957862081:android:0adc5d0a337c7cd0102240',
    messagingSenderId: '889957862081',
    projectId: 'shuttlelink-app-c593c',
    databaseURL: 'https://shuttlelink-app-c593c-default-rtdb.firebaseio.com',
    storageBucket: 'shuttlelink-app-c593c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoBIklXajXGqA-JpPAAX-LRHs6X77EEO4',
    appId: '1:889957862081:ios:3b8aac160d935aeb102240',
    messagingSenderId: '889957862081',
    projectId: 'shuttlelink-app-c593c',
    databaseURL: 'https://shuttlelink-app-c593c-default-rtdb.firebaseio.com',
    storageBucket: 'shuttlelink-app-c593c.firebasestorage.app',
    iosBundleId: 'com.example.shuttlelinkapp.shuttleLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoBIklXajXGqA-JpPAAX-LRHs6X77EEO4',
    appId: '1:889957862081:ios:3b8aac160d935aeb102240',
    messagingSenderId: '889957862081',
    projectId: 'shuttlelink-app-c593c',
    databaseURL: 'https://shuttlelink-app-c593c-default-rtdb.firebaseio.com',
    storageBucket: 'shuttlelink-app-c593c.firebasestorage.app',
    iosBundleId: 'com.example.shuttlelinkapp.shuttleLinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbKnkUgRNrkIOHVs9Px3XGzVbT25bWqjY',
    appId: '1:889957862081:web:e03db724e9a2664c102240',
    messagingSenderId: '889957862081',
    projectId: 'shuttlelink-app-c593c',
    authDomain: 'shuttlelink-app-c593c.firebaseapp.com',
    databaseURL: 'https://shuttlelink-app-c593c-default-rtdb.firebaseio.com',
    storageBucket: 'shuttlelink-app-c593c.firebasestorage.app',
  );
}
